# Generated by Django 4.2.23 on 2025-07-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduite_accompagnee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionconduite',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
